plugins: 
  - jekyll-paginate

# markdown configs
markdown: kramdown
safe: true
lsi: false
highlighter: pygments

url: "https://danboruya.github.io/blog/"
permalink: pretty
include: 
  - _pages

# pagenate configs
paginate: 5
paginate_path: "/page/:num/"
inter_post_navigation: false
