title: Research and Development Blog
description: "研究や技術のお話をしたり，忘備録的に記事を書いたりします．"
plugins: 
  - jekyll-paginate

# markdown configs
markdown: kramdown
safe: true
lsi: false

url: "https://danboruya.github.io/blog"
baseurl: ""
permalink: pretty
include: 
  - _pages

# paginate configs
paginate: 5
paginate_path: "/page/:num/"
inter_post_navigation: false

ga_tracking_id: "UA-134623824-2"
